use super::render_install_plan;
use crate::config::NetworkPolicyConfig;
use crate::sandbox_policy::{HostAddresses, compile_network};

#[test]
fn render_does_not_claim_installation_or_activation() {
    let config = NetworkPolicyConfig {
        production_cidrs: vec![],
    };
    let policy = compile_network(
        &config,
        &HostAddresses {
            addresses: vec!["203.0.113.9".parse().unwrap()],
        },
    )
    .unwrap();
    let plan = render_install_plan(&policy);
    assert_eq!(
        plan.relative_destination,
        "chimera.service.d/50-sandbox-network.conf"
    );
    assert!(plan.requires_restart);
    assert!(!plan.activation_available);
    assert!(plan.drop_in.contains("IPAddressDeny=203.0.113.9/32"));
    assert!(!plan.drop_in.contains("IPAddressAllow=any"));
}

#[test]
fn render_matches_complete_canonical_fragment() {
    let policy = compile_network(
        &NetworkPolicyConfig {
            production_cidrs: vec!["198.51.100.0/24".parse().unwrap()],
        },
        &HostAddresses {
            addresses: vec!["203.0.113.9".parse().unwrap()],
        },
    )
    .unwrap();
    let plan = render_install_plan(&policy);
    let expected = format!(
        "# Generated by chimera install-policy --render; policy-sha={}\n[Service]\nIPAddressAllow=\nIPAddressDeny=\nIPAddressDeny=0.0.0.0/8\nIPAddressDeny=10.0.0.0/8\nIPAddressDeny=127.0.0.0/8\nIPAddressDeny=169.254.0.0/16\nIPAddressDeny=172.16.0.0/12\nIPAddressDeny=192.168.0.0/16\nIPAddressDeny=198.51.100.0/24\nIPAddressDeny=203.0.113.9/32\nIPAddressDeny=224.0.0.0/4\nIPAddressDeny=255.255.255.255/32\nIPAddressDeny=::/0\n",
        policy.digest()
    );
    assert_eq!(plan.drop_in, expected);
    assert_eq!(plan.schema_version, 1);
    assert_eq!(plan.policy_digest, policy.digest());
}
