use crate::sandbox_policy::NetworkPolicy;

pub struct InstallPlan {
    pub schema_version: u32,
    pub relative_destination: String,
    pub drop_in: String,
    pub policy_digest: String,
    pub requires_restart: bool,
    pub activation_available: bool,
}

pub fn render_install_plan(policy: &NetworkPolicy) -> InstallPlan {
    let mut drop_in = format!(
        "# Generated by chimera install-policy --render; policy-sha={}\n[Service]\nIPAddressAllow=\nIPAddressDeny=\n",
        policy.digest()
    );
    for cidr in policy.denied() {
        drop_in.push_str(&format!("IPAddressDeny={cidr}\n"));
    }

    InstallPlan {
        schema_version: 1,
        relative_destination: "chimera.service.d/50-sandbox-network.conf".to_owned(),
        drop_in,
        policy_digest: policy.digest().to_owned(),
        requires_restart: true,
        activation_available: false,
    }
}

#[cfg(test)]
#[path = "install_test.rs"]
mod install_test;
